/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {
      colors: {
        'brand': '#fc5926',
        'brand-light': '#fcd2c1',
        'brand-dark': '#e64d00',
        'brand-darker': '#d44a00',
        'brand-darkest': '#c44600',
        'brand-lighter': '#fcd2c1',
        'brand-lightest': '#ffe9e6',
        'brand-neutral': '#f9f9f9',
        'brand-neutral-light': '#f9f9f9',
        'brand-neutral-dark': '#e5e5e5',
        'brand-neutral-darker': '#cccccc',
        'brand-neutral-darkest': '#b2b2b2',
        'brand-neutral-lighter': '#ffffff',
        'brand-neutral-lightest': '#ffffff',
        'brand-success': '#00b300',
        'brand-success-light': '#cce6cc',
        'brand-success-dark': '#008000',
        'brand-success-darker': '#006600',
        'brand-success-darkest': '#004d00',
        'brand-success-lighter': '#e6ffe6',
        'brand-success-lightest': '#f2fff2',
        'brand-warning': '#ffcc00',
        'brand-warning-light': '#fff2cc',
        'brand-warning-dark': '#e6b800',
        'brand-warning-darker': '#b38f00',
        'brand-warning-darkest': '#806600',
        'brand-warning-lighter': '#fff9e6',
        'brand-warning-lightest': '#fffff2',
        'brand-danger': '#ff0000',
        'brand-danger-light': '#ffcccc',
        'brand-danger-dark': '#cc0000',
        'brand-danger-darker': '#990000',
        'brand-danger-darkest': '#660000',
        'brand-danger-lighter': '#ffe6e6',
        'brand-danger-lightest': '#fff2f2',
        'brand-info': '#0066ff',
        'brand-info-light': '#cce0ff',
        'brand-info-dark': '#0047b3',
        'brand-info-darker': '#003380',
        'brand-info-darkest': '#00264d',
        'brand-info-lighter': '#e6f0ff',
        'brand-info-lightest': '#f2f7ff',
        'brand-linkedin': '#0077b5',
        'brand-linkedin-light': '#d9e5fa',
        'brand-linkedin-dark': '#005082',
        'brand-linkedin-darker': '#00395d',
        'brand-linkedin-darkest': '#002138',
        'brand-linkedin-lighter': '#e6effa',
        'brand-linkedin-lightest': '#f2f7fd',
      },
    },
  },
  plugins: [],
}

